### ISSUE TITLE
Can't save changes in /var/www on commit to a new image.

### ISSUE THREAD

**Issue by BWibo** [tum-gis/3dcitydb-web-map-docker#2]
See previous discussion here:  tum-gis/3dcitydb-docker-compose#1

**Comment by BWibo** [comment]
Possibly fixed in c4767e643d3312b67b455e52238de5eb0683a913. In the `Dockefile` a volume was created at `/var/www/` which is not needed. I believe this may have caused your issue.

@Crare:
Can you please retry with the latest devel image. Get it by running `docker pull tumgis/3dcitydb-web-map:devel`.
Please confirm if this works.

**Comment by Crare** [comment]
That seems to fix that. commit+run works with devel.

Though I get other error regarding cesium:
`Cesium.loadJson is not a function` (CitydbKmlLayer.js:292)

```
Uncaught TypeError: Cesium.loadJson is not a function
    at loadMasterJSON (CitydbKmlLayer.js:292)
    at CitydbKmlLayer.addToCesium (CitydbKmlLayer.js:363)
    at WebMap3DCityDB.addLayer (3dcitydb-web-map.js:112)
    at _loadLayer (script.js:458)
    at loadLayerGroup (script.js:455)
    at addNewExistingLayer (script.js:1571)
    at script.js:1573
```

addNewExistingLayer is my function that similar to addNewLayer, but with already setup options to load directly on startup city map in view.(json + collada kmls)

EDIT: this might be due to me editing files under /js folder. you might have different setup. I'll try leaving it out..
EDIT 2: yeah that was it.

**Comment by Crare** [comment]
it works now thanks!

**Comment by BWibo** [comment]
OK, closing. Thx for reporting and testing.
