### ISSUE TITLE
Web Map Client Pro

### ISSUE THREAD

**Issue by Chep2** [tum-gis/3dcitydb-web-map-docker#4]
Your system is very cool.
I would be very happy if you include Web Map Client Pro in docker.
It would be amazing.
Please.

**Comment by BWibo** [comment]
Hey there, 
thx, that's good to hear. The Pro version is not OpenSource and will therefore not be available as Docker image.
However, @Son-HNguyen is currently working on an full redesign of the Webclient and as far as I know, this new version will include features you may know from the pro Version, like queries on attribute values.
@Son-HNguyen is that correct?

The new version will be released as Docker when as soon as it is released.

**Comment by thomashkolbe** [comment]
Hi, thank you. The Webmap Client Pro is currently
non-functional, because Google has deactivated the older
versions of their GoogleDocs API.
We are currently planning a major rewrite of the
3DCityDB Webmap Client using the Angular framework
and will make that Open Source again. However, it may
take until next year before we can show something...

Best regards
Thomas Kolbe

**Comment by Chep2** [comment]
Thank you very much for your work.
It's incredibly cool.
I will be very happy.
